# .github/workflows/ci.yml
name: CI Pipeline
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: ecom
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d ecom"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx flake8
      - name: Run lint
        run: |
          flake8 . --max-line-length=120
      - name: Run tests
        env:
          TESTING: '1'
          DATABASE_URL: 'sqlite:///./test_ecommerce.db'
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q
      - name: Build Docker image
        run: |
          docker build . -t e-commerce-app:latest
